config/routes.rb
SunraRestApi::Application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords],
                      token_authentication_key: 'authentication_key'

  root to: 'projects#index'

  #match '/404': 'errors#not_found'
  #match '/500': 'errors#exception'

  resources :admins

  get 'search', controller: 'projects'
  resources :projects do
    resources :client_login
    resources :bookings do
      post :mark, on: :member
      resources :recordings do
        resources :recording_formats
      end
    end
  end

  resources :service_status, controller: 'service_status',
                             path_names: { index: 'overview' },
                             only: [ :index ]

  resources :recording_formats
  resources :studio_lookups
  resources :client_login

  resources :quickproject, controller: 'projects',
                           path_names: { new: 'quick' }


  # currently unused
  resources :booking_contact_details
  resources :booking_contacts
  resources :booking_companies
  resources :format_lookups
  resources :distribution_audits
  resources :file_ops_audits
end

app/views/admins/_form.html.haml
= simple_form_for(@admin) do |f|
  .row
    .col-md-12
      = f.input :email
  .row
    .col-md-12
      = f.input :password
  .row
  .row
    .col-md-7
    .col-md-5
      .btn-group
        = f.button :submit, "CREATE ADMIN", class: 'btn btn-danger ls w_220'
        = link_to 'BACK', admins_path, class: 'btn btn-success ls w_220'

app/views/admins/edit.html.haml
.container.boxed.well
  %h1{class: 'ls'}
  = render 'form'

app/views/admins/index.html.haml
.container.boxed.well
  .row
    .col-md-7
    .col-md-5
      = link_to 'CREATE NEW ADMIN', new_admin_path, class: 'btn btn-warning ls w_440' if current_admin.id == 1

%table{class: 'table container boxed well '}
  %tr
    %th ID
    %th EMAIL
    %th LAST LOGIN
    %th IP
    %th
  - @admins.each do | admin |
    %tr
      %td= admin.id
      %td= admin.email
      %td= admin.last_sign_in_at
      %td= admin.last_sign_in_ip
      %td
        .btn-group.pull-right
          - if current_admin.id == 1
            = link_to 'EDIT', edit_admin_path(admin), class: 'btn btn-warning ls w_220' 
            = link_to 'DESTROY', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger w_220 ls' if admin.id > 1
          - else
            &nbsp;
%br/

app/views/admins/new.html.haml
.container.boxed.well
  %h1{class: 'ls'} CREATE NEW ADMIN
  = render 'form'

app/views/admins/show.html.haml
%p#notice= notice
%p
  %b ID
  = @admin.id
%p
  %b EMAIL
  = @admin.email
= link_to 'Edit', edit_admin_path(@admin)
|
= link_to 'Back', admins_path