config/routes.rb
SunraRestApi::Application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords],
                      token_authentication_key: 'authentication_key'

  root to: 'projects#index'

  #match '/404': 'errors#not_found'
  #match '/500': 'errors#exception'

  resources :admins

  get 'search', controller: 'projects'
  resources :projects do
    resources :client_login
    resources :bookings do
      post :mark, on: :member
      resources :recordings do
        resources :recording_formats
      end
    end
  end

  resources :service_status, controller: 'service_status',
                             path_names: { index: 'overview' },
                             only: [ :index ]

  resources :recording_formats
  resources :studio_lookups
  resources :client_login

  resources :quickproject, controller: 'projects',
                           path_names: { new: 'quick' }


  # currently unused
  resources :booking_contact_details
  resources :booking_contacts
  resources :booking_companies
  resources :format_lookups
  resources :distribution_audits
  resources :file_ops_audits
end

app/models/booking_contact.rb
class BookingContact < ActiveRecord::Base
  belongs_to :booking_company

  attr_accessible :contact_name
  validates  :contact_name, :presence => true

  has_many :booking_contact_details, :dependent => :destroy
  validates_associated :booking_contact_details
  accepts_nested_attributes_for :booking_contact_details, allow_destroy: true
end

app/controllers/booking_contacts_controller.rb
class BookingContactsController < ApplicationController
  # GET /booking_contacts
  # GET /booking_contacts.json
  def index
    @booking_contacts = BookingContact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @booking_contacts }
    end
  end

  # GET /booking_contacts/1
  # GET /booking_contacts/1.json
  def show
    @booking_contact = BookingContact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking_contact }
    end
  end

  # GET /booking_contacts/new
  # GET /booking_contacts/new.json
  def new
    @booking_contact = BookingContact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking_contact }
    end
  end

  # GET /booking_contacts/1/edit
  def edit
    @booking_contact = BookingContact.find(params[:id])
  end

  # POST /booking_contacts
  # POST /booking_contacts.json
  def create
    @booking_contact = BookingContact.new(params[:booking_contact])

    respond_to do |format|
      if @booking_contact.save
        format.html { redirect_to @booking_contact, notice: 'Booking contact was successfully created.' }
        format.json { render json: @booking_contact, status: :created, location: @booking_contact }
      else
        format.html { render action: "new" }
        format.json { render json: @booking_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /booking_contacts/1
  # PUT /booking_contacts/1.json
  def update
    @booking_contact = BookingContact.find(params[:id])

    respond_to do |format|
      if @booking_contact.update_attributes(params[:booking_contact])
        format.html { redirect_to @booking_contact, notice: 'Booking contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_contacts/1
  # DELETE /booking_contacts/1.json
  def destroy
    @booking_contact = BookingContact.find(params[:id])
    @booking_contact.destroy

    respond_to do |format|
      format.html { redirect_to booking_contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/booking_contacts_helper.rb
module BookingContactsHelper
end

app/views/booking_contacts/_form.html.erb
<%= simple_form_for(@booking_contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :contact_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/booking_contacts/edit.html.erb
<h1>Editing booking_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking_contact %> |
<%= link_to 'Back', booking_contacts_path %>

app/views/booking_contacts/index.html.erb
<h1>Listing booking_contacts</h1>

<table>
  <tr>
    <th>Contact name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booking_contacts.each do |booking_contact| %>
  <tr>
    <td><%= booking_contact.contact_name %></td>
    <td><%= link_to 'Show', booking_contact %></td>
    <td><%= link_to 'Edit', edit_booking_contact_path(booking_contact) %></td>
    <td><%= link_to 'Destroy', booking_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking contact', new_booking_contact_path %>

app/views/booking_contacts/new.html.erb
<h1>New booking_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', booking_contacts_path %>

app/views/booking_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contact name:</b>
  <%= @booking_contact.contact_name %>
</p>


<%= link_to 'Edit', edit_booking_contact_path(@booking_contact) %> |
<%= link_to 'Back', booking_contacts_path %>