config/routes.rb
SunraRestApi::Application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords],
                      token_authentication_key: 'authentication_key'

  root to: 'projects#index'

  #match '/404': 'errors#not_found'
  #match '/500': 'errors#exception'

  resources :admins

  get 'search', controller: 'projects'
  resources :projects do
    resources :client_login
    resources :bookings do
      post :mark, on: :member
      resources :recordings do
        resources :recording_formats
      end
    end
  end

  resources :service_status, controller: 'service_status',
                             path_names: { index: 'overview' },
                             only: [ :index ]

  resources :recording_formats
  resources :studio_lookups
  resources :client_login

  resources :quickproject, controller: 'projects',
                           path_names: { new: 'quick' }


  # currently unused
  resources :booking_contact_details
  resources :booking_contacts
  resources :booking_companies
  resources :format_lookups
  resources :distribution_audits
  resources :file_ops_audits
end

app/views/shared/_admin_nav_bar.html.erb
<nav class="navbar navbar-default navbar-admin" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">TOGGLE NAVIGATION</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand ls studio_title " style="color: white" href="#"><%= SunraRestApi::Application::config.studio_name.upcase %></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="menu_header"><a href="<%= projects_path %>">PROJECTS</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle menu_header" data-toggle="dropdown">CONFIGURATION<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li><a href="<%= admins_path %>">ADMINISTRATOR LOGINS</a></li>
            <li><a href="<%= studio_lookups_path %>">STUDIO IDS</a></li>
          </ul>
        </li>
        <li>
          <a href="#" class="dropdown-toggle menu_header" data-toggle="dropdown">SERVICE STATUS<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%= service_status_path %>">OVERVIEW</a></li>
            <li><a href="">RECORDING SERVICE</a></li>
            <li><a href="">UPLOAD SERVICE</a></li>
            <li><a href="">FAILSAFE SERVICE</a></li>
            <li><a href="">COPY SERVICE</a></li>
          </ul>
        </li>
        <li class="menu-header">
        </li>
      </ul>
      <div class="navbar-right">
        <ul class="nav navbar-nav">
          <li class="menu_header"><%= link_to "SIGN OUT (#{current_admin.email}) ",
                          destroy_admin_session_path,
                          :method => :delete %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>