config/routes.rb
SunraRestApi::Application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords],
                      token_authentication_key: 'authentication_key'

  root to: 'projects#index'

  #match '/404': 'errors#not_found'
  #match '/500': 'errors#exception'

  resources :admins

  get 'search', controller: 'projects'
  resources :projects do
    resources :client_login
    resources :bookings do
      post :mark, on: :member
      resources :recordings do
        resources :recording_formats
      end
    end
  end

  resources :service_status, controller: 'service_status',
                             path_names: { index: 'overview' },
                             only: [ :index ]

  resources :recording_formats
  resources :studio_lookups
  resources :client_login

  resources :quickproject, controller: 'projects',
                           path_names: { new: 'quick' }


  # currently unused
  resources :booking_contact_details
  resources :booking_contacts
  resources :booking_companies
  resources :format_lookups
  resources :distribution_audits
  resources :file_ops_audits
end

app/models/booking_company.rb
class BookingCompany < ActiveRecord::Base
  belongs_to :project

  attr_accessible :company_name, :booking_contacts_attributes
  validates :company_name, :presence => true, :uniqueness => true

  has_many :booking_contacts, :dependent => :destroy
  validates_associated :booking_contacts
  accepts_nested_attributes_for :booking_contacts, allow_destroy: true

  has_many :booking_contact_details, :through => :booking_contacts
end

app/controllers/booking_companies_controller.rb
class BookingCompaniesController < ApplicationController
  # GET /booking_companies
  # GET /booking_companies.json
  def index
    @booking_companies = BookingCompany.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @booking_companies }
    end
  end

  # GET /booking_companies/1
  # GET /booking_companies/1.json
  def show
    @booking_company = BookingCompany.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking_company }
    end
  end

  # GET /booking_companies/new
  # GET /booking_companies/new.json
  def new
    @booking_company = BookingCompany.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking_company }
    end
  end

  # GET /booking_companies/1/edit
  def edit
    @booking_company = BookingCompany.find(params[:id])
  end

  # POST /booking_companies
  # POST /booking_companies.json
  def create
    @booking_company = BookingCompany.new(params[:booking_company])

    respond_to do |format|
      if @booking_company.save
        format.html { redirect_to @booking_company, notice: 'Booking company was successfully created.' }
        format.json { render json: @booking_company, status: :created, location: @booking_company }
      else
        format.html { render action: "new" }
        format.json { render json: @booking_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /booking_companies/1
  # PUT /booking_companies/1.json
  def update
    @booking_company = BookingCompany.find(params[:id])

    respond_to do |format|
      if @booking_company.update_attributes(params[:booking_company])
        format.html { redirect_to @booking_company, notice: 'Booking company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_companies/1
  # DELETE /booking_companies/1.json
  def destroy
    @booking_company = BookingCompany.find(params[:id])
    @booking_company.destroy

    respond_to do |format|
      format.html { redirect_to booking_companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/booking_companies_helper.rb
module BookingCompaniesHelper
end

app/views/booking_companies/_form.html.erb
<%= simple_form_for(@booking_company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_name %>
  </div>

  <h2>Add Contacts</h2>
  <div class="items form-horizontal">
    <%= f.nested_fields_for :booking_contacts do |f| %>
      <fieldset class="item">
        <%= f.label :name %>
        <%= f.text_field :contact_name %>

        <a href="#" class="remove btn btn-danger">remove</a>

        <%= f.hidden_field :id %>
        <%= f.hidden_field :_destroy %>
      </fieldset>
    <% end %>
  </div>
  <a href="#" class="add btn">+ add new contact</a>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/booking_companies/edit.html.erb
<h1>Editing booking_company</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking_company %> |
<%= link_to 'Back', booking_companies_path %>

app/views/booking_companies/index.html.erb
<h1>Listing booking_companies</h1>

<table class="table table-striped">
  <tr>
    <th>Company name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booking_companies.each do |booking_company| %>
  <tr>
    <td><%= booking_company.company_name %></td>
    <td><%= link_to 'Show', booking_company %></td>
    <td><%= link_to 'Edit', edit_booking_company_path(booking_company) %></td>
    <td><%= link_to 'Destroy', booking_company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking company', new_booking_company_path %>

app/views/booking_companies/new.html.erb
<h1>New booking_company</h1>

<%= render 'form' %>

<%= link_to 'Back', booking_companies_path %>

app/views/booking_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @booking_company.company_name %>
</p>


<%= link_to 'Edit', edit_booking_company_path(@booking_company) %> |
<%= link_to 'Back', booking_companies_path %>